# Generated by Django 5.2.6 on 2025-10-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
        migrations.RemoveField(
            model_name='receiver',
            name='address',
        ),
        migrations.RemoveField(
            model_name='receiver',
            name='email',
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('viewer', 'Viewer')], default='viewer', max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('bin', 'Bin')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='receiver',
            name='id_card_number',
            field=models.CharField(default='UNKNOWN', max_length=50),
        ),
        migrations.AddField(
            model_name='receiver',
            name='id_card_type',
            field=models.CharField(default='UNKNOWN', max_length=50),
        ),
        migrations.AddField(
            model_name='receiver',
            name='office_address',
            field=models.TextField(default='UNKNOWN'),
        ),
        migrations.AddField(
            model_name='receiver',
            name='office_name',
            field=models.CharField(default='UNKNOWN', max_length=255),
        ),
        migrations.AddField(
            model_name='receiver',
            name='phone_number',
            field=models.CharField(default='UNKNOWN', max_length=20),
        ),
        migrations.AddField(
            model_name='receiver',
            name='post',
            field=models.CharField(default='UNKNOWN', max_length=255),
        ),
        migrations.AddField(
            model_name='receiver',
            name='vehicle_number',
            field=models.CharField(default='UNKNOWN', max_length=50),
        ),
        migrations.AlterField(
            model_name='branch',
            name='organization_id',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
