# Generated by Django 5.2.6 on 2025-10-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_of_measurement',
            field=models.CharField(choices=[('nos', 'Nos.'), ('set', 'Set'), ('kg', 'KG'), ('ltr', 'Ltr'), ('pcs', 'Pcs')], default='nos', max_length=10),
        ),
    ]
