# Generated by Django 5.2.6 on 2025-10-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4'), ('5', 'Level 5'), ('6', 'Level 6'), ('7', 'Level 7'), ('8', 'Level 8'), ('9', 'Level 9')], default='1', max_length=1),
        ),
    ]
