# Generated by Django 5.2.6 on 2025-10-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_branch_account_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_active_products', models.IntegerField(default=0)),
                ('total_active_branches', models.IntegerField(default=0)),
                ('total_active_offices', models.IntegerField(default=0)),
                ('total_active_employees', models.IntegerField(default=0)),
                ('total_receivers', models.IntegerField(default=0)),
                ('total_letters', models.IntegerField(default=0)),
                ('total_draft_letters', models.IntegerField(default=0)),
                ('total_sent_letters', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dashboard Statistics',
                'verbose_name_plural': 'Dashboard Statistics',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='receiver',
            name='id_card_type',
            field=models.CharField(choices=[('national_id', 'National Identity Card'), ('citizenship', 'Citizenship Certificate'), ('voter_id', 'Voter ID Card'), ('passport', 'Passport / E-Passport'), ('drivers_license', 'Driver’s License'), ('pan_card', 'PAN Card'), ('unknown', 'UNKNOWN')], default='unknown', max_length=20),
        ),
    ]
