# Generated by Django 5.2.6 on 2025-10-26 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='content',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='title',
        ),
        migrations.AddField(
            model_name='letter',
            name='chalani_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='letter',
            name='date',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='letter',
            name='gatepass_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='letter',
            name='letter_count',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='letter',
            name='receiver_address',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='letter',
            name='receiver_id_card_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='letter',
            name='receiver_id_card_type',
            field=models.CharField(blank=True, choices=[('unknown', 'Unknown'), ('national_id', 'National ID'), ('citizenship', 'Citizenship'), ('voter_id', 'Voter ID'), ('passport', 'Passport'), ('drivers_license', "Driver's License"), ('pan_card', 'PAN Card')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='letter',
            name='receiver_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='letter',
            name='receiver_office_address',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='letter',
            name='receiver_office_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='letter',
            name='receiver_phone_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='letter',
            name='receiver_post',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='letter',
            name='receiver_vehicle_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='letter',
            name='request_chalani_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='letter',
            name='request_date',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='letter',
            name='request_letter_count',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='letter',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='letter',
            name='voucher_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='LetterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=500)),
                ('company', models.CharField(max_length=200)),
                ('serial_number', models.CharField(max_length=100)),
                ('unit_of_measurement', models.CharField(blank=True, default='', max_length=50)),
                ('quantity', models.CharField(max_length=100)),
                ('remarks', models.CharField(blank=True, default='', max_length=500)),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myapp.letter')),
            ],
            options={
                'ordering': ['serial_number'],
                'unique_together': {('letter', 'serial_number')},
            },
        ),
    ]
