# Generated by Django 5.2.6 on 2025-11-18 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='office_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='letter',
            name='sub_office_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
