# Generated by Django 5.2.6 on 2025-11-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_letter_office_name_letter_sub_office_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
