# Generated by Django 5.2.6 on 2025-11-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_employee_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('accountant', 'Accountant'), ('viewer', 'Viewer')], default='viewer', max_length=20),
        ),
    ]
