# Generated by Django 5.2.6 on 2025-11-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_employee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='letteritem',
            name='product_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
