# Generated by Django 5.2.6 on 2025-11-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_letteritem_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='receiver_id_card_type',
            field=models.CharField(blank=True, choices=[('unknown', 'Unknown'), ('national_id', 'National ID'), ('citizenship', 'Citizenship'), ('voter_id', 'Voter ID'), ('passport', 'Passport'), ('drivers_license', "Driver's License"), ('pan_card', 'PAN Card'), ('employee_id', 'EMPLOYEE ID')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='receiver',
            name='id_card_type',
            field=models.CharField(choices=[('national_id', 'National Identity Card'), ('citizenship', 'Citizenship Certificate'), ('voter_id', 'Voter ID Card'), ('passport', 'Passport / E-Passport'), ('drivers_license', "Driver's License"), ('pan_card', 'PAN Card'), ('unknown', 'UNKNOWN'), ('employee_id', 'EMPLOYEE ID')], default='unknown', max_length=20),
        ),
    ]
