# Generated by Django 5.2.6 on 2025-12-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_letter_receiver_id_card_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letteritem',
            name='serial_number',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_of_measurement',
            field=models.CharField(choices=[('nos', 'Nos.'), ('set', 'Set'), ('pair', 'Pair'), ('meter', 'Meter'), ('kg', 'KG'), ('ltr', 'Litre'), ('rim', 'Rim'), ('pad', 'Pad'), ('dozen', 'Dozen'), ('kms', 'KMS'), ('cu_meter', 'CU. METER'), ('pcs', 'Pcs'), ('rolls', 'Rolls'), ('bottles', 'Bottles'), ('packets', 'Packets'), ('sq_ft', 'SQ. FT.'), ('ft', 'FT.'), ('coil', 'Coil')], default='nos', max_length=20),
        ),
    ]
