# Generated by Django 5.2.6 on 2026-01-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_letteritem_serial_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='office_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='letter',
            name='receiver_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='receiver',
            name='id_card_type',
            field=models.CharField(choices=[('national_id', 'राष्ट्रिय परिचयपत्र'), ('citizenship', 'नागरिकता प्रमाणपत्र'), ('voter_id', 'मतदाता परिचयपत्र'), ('passport', 'राहदानी / ई–राहदानी'), ('drivers_license', 'सवारी चालक अनुमति पत्र'), ('pan_card', 'स्थायी लेखा नम्बर (प्यान)'), ('unknown', 'अज्ञात'), ('employee_id', 'कर्मचारी परिचयपत्र')], default='unknown', max_length=20),
        ),
    ]
