# Generated by Django 5.2.6 on 2026-03-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_letter_office_id_letter_receiver_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='letteritem',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='letteritem',
            constraint=models.UniqueConstraint(condition=models.Q(('serial_number', '-'), _negated=True), fields=('letter', 'serial_number'), name='unique_letter_serial_number'),
        ),
    ]
