# Generated by Django 5.2.6 on 2026-03-20 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_letteritem_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='letteritem',
            name='unique_letter_serial_number',
        ),
        migrations.AddConstraint(
            model_name='letteritem',
            constraint=models.UniqueConstraint(condition=models.Q(('serial_number', '-'), _negated=True), fields=('letter', 'serial_number', 'name'), name='unique_letter_serial_number_name'),
        ),
    ]
